baseURL = "https://duffney.io"
languageCode = "en-us"
title = "duffney.io"
theme= "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 15
disableReadOtherPosts = true

googleAnalytics = "UA-173628310-1"
disqusShortname = "duffney"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Follow me on Twitter. Binge my videos on YouTube. Or checkout my code on GitHub"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you link
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

# Colors for favicons
[params.favicon.color]
  mask = "#252627"
  msapplication = "#252627"
  theme = "#252627"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = ""
    subtitle = "duffney.io"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "_ duffney.io"
      logoHomeLink = "/"

[params.portrait]
  path = "/img/displaypic30.png"
  alt = "Portrait"

[permalinks]
  posts = "/:title"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/joshduffney"
  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/channel/UCCV1T7JbfzbE2O7P3kydmKw"
  [[params.social]]
    name = "github"
    url  = "https://github.com/Duffney"

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  # And you can even create generic menu
  [[menu.main]]
    identifier = "About"
    name       = "about"
    url        = "/about"
  [[menu.main]]
    identifier = "Posts"
    name       = "posts"
    url        = "/posts"

