[build]
publish = "public"
command = "hugo --gc --minify"

[[redirects]]
  from = "/time-blocking-in-obsidian"
  to = "https://theknowledgeworker.substack.com/p/time-blocking-in-obsidian"
  status = 301
  force = true

[[redirects]]
  from = "/how-to-take-smart-notes-in-obsidian"
  to = "https://theknowledgeworker.substack.com/p/how-to-take-smart-notes-in-obsidian"
  status = 301
  force = true